### ISSUE TITLE
Isn't showing any confirmation after entering contact details for checkout

### ISSUE THREAD

**Issue by Rajinsharwar** [grapeJUICE1/burgers-on-you#2]
When the burger is ordered, and we proceed to the checkout, some information about the order needs to be entered. After those information has been entered, no confirmation is shown like "Thanks for your order" etc. It's confusing to be in a loop of orders instead of getting any generic message for order confirmation.

**Comment by grapeJUICE1** [comment]
Yes , I do agree . I didn't think about it tbh. The order does show up in the orders page but yeah a confirmation notification (also an email maybe) can be great. 
I'll think of implementing this.
